[services.rss]
limit = 10

[params]
dateFmt = "2006-01-02"
description = "实在是高的个人技术博客"
favicon = ""
subtitle = "Find, discover, explorer and enjoy!"

# Customize the text of the 404 page here
errorPageText = "There's nothing to see here, please move along!"

# Header with title/subtitle can be disabled here.
# (If you disable this, add some link on the index page inside menu.main,
#  otherwise your visitors will get confused and lost...)
showNavHeader = true

# Decide if only summaries are shown on the main page or the full content
showFullContent = true

# If false no pagination is shown when there is nothing to paginate
showEmptyPagination = true

# If false the dates for the posts are not shown
showMetaDates = true

# If false the taxonomy links for the posts are not shown
showMetaLinks = true

# Uses Hugo internal templates if set
opengraph = false
schema = false
twitter_cards = false

# 百度访问统计
baiduAnalysis = "815a521e3c0aee7749c5f8350acb8c6d"

[menu]
[[menu.main]]
identifier = "posts"
name = "Posts"
title = "All posts"
url = "/posts/"
weight = 1
[[menu.main]]
identifier = "tags"
name = "Tags"
title = "All tags"
url = "/tags/"
weight = 2
[[menu.main]]
identifier = "series"
name = "Series"
title = "All series"
url = "/series/"
weight = 3
[[menu.main]]
identifier = "categories"
name = "Categories"
title = "All categories"
url = "/categories/"
weight = 4
[[menu.main]]
identifier = "about"
name = "About"
title = "About me"
url = "/about/"
weight = 5

[[menu.meta]]
identifier = "categories"
name = "Categories"
weight = 1
[[menu.meta]]
identifier = "series"
name = "Series"
weight = 2
[[menu.meta]]
identifier = "tags"
name = "Tags"
weight = 3

[[menu.footer]]
name = "GitHub"
title = "My repository"
url = "https://github.com/amazing-gao"
weight = 1
